### ISSUE TITLE
Can't see folders / server down

### ISSUE THREAD

**Issue by ghost** [einsteinx2/WaveBoxWebClient#5]
As in the topic. I can browse artists and albums, but folder screen remains empty.
Nothing special in the log. 
https://www.dropbox.com/s/xduazgl41jka49k/wevebox%20logs%202013.08.04_v2.txt

Then I go back to artists (OK), then albums and... I can't see anything there either. Not sure if it's processing them, sending, etc. Probably processing, as Wavebox is constantly at 40% CPU. After 2 minutes still nothing.
Then I try to go to the main page and apparently the server is down, not responding.

ps. it'd be great to have any "loading" indicator on these pages.
ps2. I have way more than 1000 albums.

**Comment by ghost** [comment]
If it's performance, pls move to the server forum.

**Comment by ghost** [comment]
Actually... I found some issues with inserting values into Folders table. Slashes again? I'm on Win, as you can see.

https://www.dropbox.com/s/x5e4fss8q1ozuvq/wevebox%20logs%203013.08.04_v3.txt

**Comment by justindhill** [comment]
Well, that does make me think it's a server issue, so I'll move it there. My intuition tells me it's not a slashes issue (I've successfully scanned on Windows before) because it's only on some songs. I haven't done much work on the server in the last few months, as I've been focused on the web interface, so I'm only of limited use in that department.
